export default{
    applyDraw:{
        route:"/dist_store/pages/applyDraw/index",
        desc:"申请提现"
    },
    balanceDetail:{
        route:"/dist_store/pages/balanceDetail/index",
        desc:"余额明细"
    },
    drawRecord:{
        route:"/dist_store/pages/drawRecord/index",
        desc:"提现记录"
    },
    goodsDetail:{
        route:"/dist_store/pages/goodsDetail/index",
        desc:"订单详情"
    },
    goodsList:{
        route:"/dist_store/pages/goodsList/index",
        desc:"分包首页，商品列表"
    },
    mine:{
        route:"/dist_store/pages/mine/index",
        desc:"我的页面"
    },
    record:{
        route:"/dist_store/pages/record/index",
        desc:"支出，收入统计页面",
        param:{
            type: "OUT" || "IN"
        }
    },
    statistical:{
        route:"/dist_store/pages/statistical/index",
        desc:"统计页面，分包的bar"
    },
    withdraw:{
        route:"/dist_store/pages/withdraw/index",
        desc:"提现页面"
    }
}